### ISSUE TITLE
Sample configuration page shows invalid value for the "open_firewall" property

### ISSUE THREAD

**Issue by DanielCMiranda** [GoogleCloudPlatform/security-response-automation#194]
Hello!

The [sample configuration yaml file](https://github.com/GoogleCloudPlatform/security-response-automation/wiki/Sample-configuration) in the Wiki page of the project currently shows an invalid value for the **open_firewall** property.

I.e:

```
properties:
  dry_run: true
  open_firewall:
    - disable
```

Since the **open_firewall** property doesn't expect a list of items, this configuration causes a parsing error. Based on the [automations.md](https://github.com/GoogleCloudPlatform/security-response-automation/blob/master/automations.md) file, I believe a valid configuration would be something like the code below:

```
properties:
  dry_run: true
  open_firewall:
    remediation_action: disable
```

**Comment by tomscript** [comment]
thanks Daniel! this has been fixed, nice catch.
- https://github.com/GoogleCloudPlatform/security-response-automation/wiki/Sample-configuration

**Comment by DanielCMiranda** [comment]
> thanks Daniel! this has been fixed, nice catch.
> 
> * https://github.com/GoogleCloudPlatform/security-response-automation/wiki/Sample-configuration

Hi @tomscript, thanks for the quick reply!

I just checked the Wiki and apparently it is still invalid.

Currently it is as shown below:

```
properties:
  dry_run: true
  remediation_action:
    - disable
```

I tested the following configuration and it works:

```
properties:
  dry_run: true
  open_firewall:
    remediation_action: disable
```
